CREATE TABLE `data_platform_invoice_document_header_data`
(
    `InvoiceDocument`                     int(16) NOT NULL,
    `SupplyChainRelationshipID`           int(16) NOT NULL,
    `SupplyChainRelationshipBillingID`    int(4) NOT NULL,
    `SupplyChainRelationshipPaymentID`    int(2) NOT NULL,
    `Buyer`                               int(12) NOT NULL,
    `Seller`                              int(12) NOT NULL,
    `BillToParty`                         int(12) NOT NULL,
    `BillFromParty`                       int(12) NOT NULL,
    `BillToCountry`                       varchar(3) NOT NULL,
    `BillFromCountry`                     varchar(3) NOT NULL,
    `Payer`                               int(12) NOT NULL,
    `Payee`                               int(12) NOT NULL,
    `InvoiceDocumentDate`                 date NOT NULL,
    `InvoiceDocumentTime`                 time NOT NULL,
    `InvoicePeriodStartDate`              date NOT NULL,
    `InvoicePeriodEndDate`                date NOT NULL,
    `AccountingPostingDate`               date DEFAULT NULL,
    `IsExportImport`                      tinyint(1) DEFAULT NULL,
    `HeaderBillingIsConfirmed`            tinyint(1) DEFAULT NULL,
    `HeaderBillingConfStatus`             varchar(2) DEFAULT NULL,
    `TotalNetAmount`                      float(13) NOT NULL,
    `TotalTaxAmount`                      float(13) NOT NULL,
    `TotalGrossAmount`                    float(13) NOT NULL,
    `TransactionCurrency`                 varchar(5) NOT NULL,
    `Incoterms`                           varchar(3) DEFAULT NULL,
    `PaymentTerms`                        varchar(4) NOT NULL,
    `DueCalculationBaseDate`              date DEFAULT NULL,
    `PaymentDueDate`                      date DEFAULT NULL,
    `NetPaymentDays`                      int(3) DEFAULT NULL,
    `PaymentMethod`                       varchar(1) NOT NULL,
    `DocumentHeaderText`                  varchar(200) DEFAULT NULL,
    `HeaderIsCleared`                     tinyint(1) DEFAULT NULL,
    `HeaderPaymentBlockStatus`            tinyint(1) DEFAULT NULL,
    `HeaderPaymentRequisitionIsCreated`   tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`           varchar(100) DEFAULT NULL,
    `CreationDate`                        date NOT NULL,
    `CreationTime`                        time NOT NULL,
    `LastChangeDate`                      date NOT NULL,
    `LastChangeTime`                      time NOT NULL,
    `IsCancelled`                         tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`InvoiceDocument`),

    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataSCRBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_scr_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataSCRPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataBillToCountry_fk` FOREIGN KEY (`BillToCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
	CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataBillFromCountry_fk` FOREIGN KEY (`BillFromCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),    
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DataPlatformInvoiceDocumentHeaderDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
