CREATE TABLE `data_platform_invoice_document_header_data`
(
    `InvoiceDocument`                     int(16) NOT NULL,
    `SupplyChainRelationshipID`           int(16) NOT NULL,
    `SupplyChainRelationshipBillingID`    int(4) NOT NULL,
    `SupplyChainRelationshipPaymentID`    int(2) NOT NULL,
    `Buyer`                               int(12) NOT NULL,
    `Seller`                              int(12) NOT NULL,
    `BillToParty`                         int(12) NOT NULL,
    `BillFromParty`                       int(12) NOT NULL,
    `BillToCountry`                       varchar(3) NOT NULL,
    `BillFromCountry`                     varchar(3) NOT NULL,
    `Payer`                               int(12) NOT NULL,
    `Payee`                               int(12) NOT NULL,
    `InvoiceDocumentDate`                 date NOT NULL,
    `InvoiceDocumentTime`                 time NOT NULL,
    `InvoicePeriodStartDate`              date NOT NULL,
    `InvoicePeriodEndDate`                date NOT NULL,
    `AccountingPostingDate`               date DEFAULT NULL,
    `IsExportImport`                      tinyint(1) DEFAULT NULL,
    `HeaderBillingIsConfirmed`            tinyint(1) DEFAULT NULL,
    `HeaderBillingConfStatus`             varchar(2) DEFAULT NULL,
    `TotalNetAmount`                      float(13) NOT NULL,
    `TotalTaxAmount`                      float(13) NOT NULL,
    `TotalGrossAmount`                    float(13) NOT NULL,
    `TransactionCurrency`                 varchar(5) NOT NULL,
    `Incoterms`                           varchar(3) DEFAULT NULL,
    `PaymentTerms`                        varchar(4) NOT NULL,
    `DueCalculationBaseDate`              date DEFAULT NULL,
    `PaymentDueDate`                      date DEFAULT NULL,
    `NetPaymentDays`                      int(3) DEFAULT NULL,
    `PaymentMethod`                       varchar(1) NOT NULL,
    `Contract`                            int(16) DEFAULT NULL,
    `ContractItem`                        int(6) DEFAULT NULL,
    `DocumentHeaderText`                  varchar(200) DEFAULT NULL,
    `HeaderIsCleared`                     tinyint(1) DEFAULT NULL,
    `HeaderPaymentBlockStatus`            tinyint(1) DEFAULT NULL,
    `HeaderPaymentRequisitionIsCreated`   tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`           varchar(100) DEFAULT NULL,
    `CertificateAuthorityChain`           varchar(2000) DEFAULT NULL,
    `UsageControlChain`                   varchar(2000) DEFAULT NULL,
    `CreationDate`                        date NOT NULL,
    `CreationTime`                        time NOT NULL,
    `LastChangeDate`                      date NOT NULL,
    `LastChangeTime`                      time NOT NULL,
    `IsCancelled`                         tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`InvoiceDocument`),

    CONSTRAINT `DPFMInvoiceDocumentHeaderDataSCRBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_scr_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataSCRPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataBillToCountry_fk` FOREIGN KEY (`BillToCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
	CONSTRAINT `DPFMInvoiceDocumentHeaderDataBillFromCountry_fk` FOREIGN KEY (`BillFromCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),    
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataContract_fk` FOREIGN KEY (`Contract`) REFERENCES `data_platform_contract_header_data` (`Contract`),
    CONSTRAINT `DPFMInvoiceDocumentHeaderDataContractItem_fk` FOREIGN KEY (`Contract`, `ContractItem`) REFERENCES `data_platform_contract_item_data` (`Contract`, `ContractItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
