CREATE TABLE `data_platform_invoice_document_item_data`
(
    `InvoiceDocument`                   		int(16) NOT NULL,
    `InvoiceDocumentItem`               		int(6) NOT NULL,
    `InvoiceDocumentItemCategory`       		varchar(4) NOT NULL,
	`SupplyChainRelationshipID`                 int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`         int(6) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryPlantID`    int(4) DEFAULT NULL,
    `InvoiceDocumentItemText`           		varchar(200) DEFAULT NULL,
    `InvoiceDocumentItemTextByBuyer`    		varchar(200) NOT NULL,
    `InvoiceDocumentItemTextBySeller`   		varchar(200) NOT NULL,
    `Product`                           		varchar(40) NOT NULL,
    `SizeOrDimensionText`                       varchar(100) DEFAULT NULL,
    `ProductGroup`                      		varchar(9) DEFAULT NULL,
    `ProductStandardID`                 		varchar(18) DEFAULT NULL,
    `ItemBillingIsConfirmed`            		tinyint(1) DEFAULT NULL,
    `Buyer`                             		int(12) NOT NULL,
    `Seller`                            		int(12) NOT NULL,
    `DeliverToParty`                    		int(12) DEFAULT NULL,
    `DeliverFromParty`                  		int(12) DEFAULT NULL,
    `DeliverToPlant`                      		varchar(4) DEFAULT NULL,
    `DeliverToPlantStorageLocation`       		varchar(4) DEFAULT NULL,
    `DeliverFromPlant`                     		varchar(4) DEFAULT NULL,
    `DeliverFromPlantStorageLocation`      		varchar(4) DEFAULT NULL,
    `ProductionPlantBusinessPartner`    		int(12) DEFAULT NULL,
    `ProductionPlant`                   		varchar(4) DEFAULT NULL,
    `ProductionPlantStorageLocation`    		varchar(4) DEFAULT NULL,
    `ServicesRenderedDate`              		date DEFAULT NULL,
    `InvoiceQuantity`                   		float(15) NOT NULL,
    `InvoiceQuantityUnit`                		varchar(3) NOT NULL,
    `InvoiceQuantityInBaseUnit`         		float(15) NOT NULL,
    `BaseUnit`                          		varchar(3) NOT NULL,
    `DeliveryUnit`                        		varchar(3) DEFAULT NULL,
    `ActualGoodsIssueDate`              		date DEFAULT NULL,
    `ActualGoodsIssueTime`              		time DEFAULT NULL,
    `ActualGoodsReceiptDate`            		date DEFAULT NULL,
    `ActualGoodsReceiptTime`            		time DEFAULT NULL,
    `ItemGrossWeight`                   		float(15) DEFAULT NULL,
    `ItemNetWeight`                     		float(15) DEFAULT NULL,
    `ItemWeightUnit`                    		varchar(3) DEFAULT NULL,
    `NetAmount`                         		float(13) NOT NULL,
    `TaxAmount`                         		float(13) NOT NULL,
    `GrossAmount`                       		float(13) NOT NULL,
    `GoodsIssueOrReceiptSlipNumber`     		varchar(35) DEFAULT NULL,
    `TransactionCurrency`               		varchar(5) DEFAULT NULL,
    `PricingDate`                       		date DEFAULT NULL,
    `TransactionTaxClassification`              varchar(1) NOT NULL,
    `ProductTaxClassificationBillToCountry`		varchar(1) NOT NULL,
    `ProductTaxClassificationBillFromCountry`	varchar(1) NOT NULL,
    `DefinedTaxClassification`                  varchar(1) NOT NULL,
    `Project`                                   int(16) DEFAULT NULL,
    `WBSElement`                                int(8) DEFAULT NULL,
    `OrderID`                           		int(16) DEFAULT NULL,
    `OrderItem`                         		int(6) DEFAULT NULL,
    `Contract`                                  int(16) DEFAULT NULL,
    `ContractItem`                              int(6) DEFAULT NULL,
    `OrderType`                         		varchar(3) DEFAULT NULL,
    `ContractType`                      		varchar(4) DEFAULT NULL,
    `OrderVaridityStartDate`            		date DEFAULT NULL,
    `OrderVaridityEndDate`              		date DEFAULT NULL,
    `InvoicePeriodStartDate`             		date DEFAULT NULL,
    `InvoicePeriodEndDate`               		date DEFAULT NULL,
    `DeliveryDocument`                  		int(16) DEFAULT NULL,
    `DeliveryDocumentItem`              		int(6) DEFAULT NULL,
    `OriginDocument`                    		int(16) DEFAULT NULL,
    `OriginDocumentItem`                		int(6) DEFAULT NULL,
    `ReferenceDocument`                			int(16) DEFAULT NULL,
    `ReferenceDocumentItem`             		int(6) DEFAULT NULL,
    `TaxCode`                           		varchar(2) DEFAULT NULL,
    `TaxRate`                           		float(6) DEFAULT NULL,
    `CountryOfOrigin`                   		varchar(3) DEFAULT NULL,
    `CountryOfOriginLanguage`                   varchar(2) DEFAULT NULL,
    `Equipment`                                 int(20) DEFAULT NULL,
    `ItemPaymentRequisitionIsCreated`   		tinyint(1) DEFAULT NULL,
    `ItemIsCleared`                             tinyint(1) DEFAULT NULL,
    `ItemPaymentBlockStatus`            		tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`         		varchar(100) DEFAULT NULL,
    `ExternalReferenceDocumentItem`     		varchar(10) DEFAULT NULL,
    `CreationDate`                              date NOT NULL,
    `CreationTime`                              time NOT NULL,
    `LastChangeDate`                            date NOT NULL,
    `LastChangeTime`                            time NOT NULL,
    `IsCancelled`                               tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`InvoiceDocument`, `InvoiceDocumentItem`),
    
    CONSTRAINT `DPFMInvoiceDocumentItemData_fk` FOREIGN KEY (`InvoiceDocument`) REFERENCES `data_platform_invoice_document_header_data` (`InvoiceDocument`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataSCRDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_scr_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    -- CONSTRAINT `DPFMInvoiceDocumentItemDataSCRDeliveryPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`), too long
    CONSTRAINT `DPFMInvoiceDocumentItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataProductionPlant_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataInvoiceQuantityUnit_fk` FOREIGN KEY (`InvoiceQuantityUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataItemWeightUnit_fk` FOREIGN KEY (`ItemWeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataContract_fk` FOREIGN KEY (`Contract`) REFERENCES `data_platform_contract_header_data` (`Contract`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataContractItem_fk` FOREIGN KEY (`Contract`, `ContractItem`) REFERENCES `data_platform_contract_item_data` (`Contract`, `ContractItem`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataDeliveryDocumentItem_fk` FOREIGN KEY (`DeliveryDocument`, `DeliveryDocumentItem`) REFERENCES `data_platform_delivery_document_item_data` (`DeliveryDocument`, `DeliveryDocumentItem`),
    -- CONSTRAINT `DPFMInvoiceDocumentItemDataTaxCode_fk` FOREIGN KEY (`TaxCode`) REFERENCES `data_platform_tax_code_tax_code_data` (`TaxCode`),　　不明
    CONSTRAINT `DPFMInvoiceDocumentItemDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`),
    CONSTRAINT `DPFMInvoiceDocumentItemDataEquipment_fk` FOREIGN KEY (`Equipment`) REFERENCES `data_platform_equipment_master_general_data` (`Equipment`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
